### ISSUE TITLE
Game with AI - error

### ISSUE THREAD

**Issue by Kduszynska** [pawel150199/chess-ai#14]
Finding best move...
Traceback (most recent call last):
  File "/Users/kasiaduszynska/Desktop/Szachy/src/run.py", line 4, in <module>
    main.mainloop()
  File "/Users/kasiaduszynska/Desktop/Szachy/src/main.py", line 221, in mainloop
    move = ai.eval(board)
  File "/Users/kasiaduszynska/Desktop/Szachy/src/ai.py", line 130, in eval
    eval, move = self.minimax(main_board, self.depth, False, -math.inf, math.inf)
  File "/Users/kasiaduszynska/Desktop/Szachy/src/ai.py", line 112, in minimax
    if not best_move:
UnboundLocalError: local variable 'best_move' referenced before assignment
(base) kasiaduszynska@air-kasia Szachy % 
<img width="824" alt="Zrzut ekranu 2024-06-10 o 10 39 13" src="https://github.com/pawel150199/chess-ai/assets/103599351/898b564e-3192-49a8-8806-e36f91909433">

**Comment by pawel150199** [comment]
MR #16 should solve the issue.
